# Site settings
title:          realsung
description:    "Hi :)"
baseurl:        ""
url:            "https://realsung.github.io"

# Google Analytics
google_analytics: UA-125826027-1

# Author
author:
  name:         realsung
  url:          https://realsung.github.io
  email:        sungjun0208@naver.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
